### ISSUE TITLE
Paid version

### ISSUE THREAD

**Issue by yyyc514** [dvandersluis/amcharts.rb#5]
Is there a whole different set of JS for the paid version or is there some way to easily turn off the advertisement with a setting?  We already own the whole product, but I liked the idea of using the gem.

**Comment by dvandersluis** [comment]
I can't include the paid version in the gem obviously, but as mentioned in the readme, if you have paid for the commercial version, take the javascript files from amcharts and put them into a `javascripts/amcharts` directory within one of your app's asset paths (assuming you're using asset pipeline), and they will be used instead of the free ones bundled in the gem.

**Comment by yyyc514** [comment]
Sorry, guess I missed that.

**Comment by dvandersluis** [comment]
No worries, hope it fixed your issue! :smile:
